steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'functions'

  # Build functions
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'functions'

  # Deploy using gcloud CLI (already authenticated in Cloud Build)
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: bash
    args:
      - '-c'
      - |
        # Install Node.js and npm in the gcloud image
        apt-get update
        apt-get install -y curl
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs

        # Install Firebase CLI
        npm install -g firebase-tools

        # Deploy functions (Cloud Build is already authenticated)
        cd /workspace
        firebase deploy --only functions --project l-apply --non-interactive --force
    env:
      - 'ORGANIZATION_ID=org_MMWWMU8RmzWKdvXctUCwKTZfD453'
      - 'LIFF_ID=2008405494-nKEy7Pl0'

timeout: 1600s

options:
  logging: CLOUD_LOGGING_ONLY
