steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'functions'

  # Build functions
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']
    dir: 'functions'

  # Install Firebase CLI and deploy
  - name: 'node:20'
    entrypoint: bash
    args:
      - '-c'
      - |
        npm install -g firebase-tools
        firebase deploy --only functions --token "$_FIREBASE_TOKEN" --project l-apply
    env:
      - 'ORGANIZATION_ID=org_MMWWMU8RmzWKdvXctUCwKTZfD453'
      - 'LIFF_ID=2008405494-nKEy7Pl0'

timeout: 1600s

options:
  logging: CLOUD_LOGGING_ONLY
